version: "3.7"

services:

  db:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend


  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - backend
    

networks:
  backend:
    driver: bridge
