version: "3.7"

services:

  db:

    image: postgres:latest

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: postgres

      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

    ports:

      - "5432:5432"

    volumes:

      - ~/.docker/volumes/postgres:/var/lib/postgresql/data

    networks:

      - backend

  #web:

 #   build:

   #   context: .

   #   dockerfile: Dockerfile

#    volumes:

#      - .:/app

 #   ports:

  #    - "8080"

  #  depends_on:

  #    - db

  #  networks:

  #    - backend

networks:
  
    backend:
  
      driver: bridge